version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers:
      - 'austintoddj'
    labels:
      - 'github-actions'
      - 'dependencies'
    commit-message:
      prefix: 'chore(deps)'

  # Maintain dependencies for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers:
      - 'austintoddj'
    labels:
      - 'npm'
      - 'dependencies'
    commit-message:
      prefix: 'chore(deps)'

  # Maintain dependencies for Composer
  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers:
      - 'austintoddj'
    labels:
      - 'composer'
      - 'dependencies'
    commit-message:
      prefix: 'chore(deps)'
